# Generated by Django 5.0 on 2023-12-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_book_author_book_is_bestselling_alter_book_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
